summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2 
bin-url: https://github.com/leleliu008/uppm-package-repository-netbsd-10.0-amd64/releases/download/2025.07.25/pkg-config-0.29.2-netbsd-10.0-amd64.release.tar.xz 
bin-sha: 3e6703cb6c79410333fe1f9b6472e00ebe7c83218d39db796aa168bca2fc5b78
